### PR TITLE
3.8.6

### PR DESCRIPTION
**Pull request by neroux**

### CODE REVIEW

**Comment by neroux** [comment]
@igr

**Comment by igr** [comment]
wow, for some reasons Im not getting emails from github!

**Comment by igr** [comment]
Hey @neroux sorry for late response, I started getting a _huge_ amount of notifications from GitHub (due to Automatic watching) and I must turn off email notification...

Fixed everything now!

Give me a few days, it might be 3.8.7 soon :)))

**Comment by neroux** [comment]
@igr 3.8.7 would be certainly nice :) but for now I think it would be important to have the 3.8.6 link there, people still download 3.8.5 otherwise.

**Comment by neroux** [comment]
@igr

**Comment by igr** [comment]
Sorry @neroux, you are completely right; the new version is out.

**Pull request closed without merging**
